services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=harry48225
      - DOCKER_INFLUXDB_INIT_PASSWORD=octopodes
      - DOCKER_INFLUXDB_INIT_ORG=seabed
      - DOCKER_INFLUXDB_INIT_BUCKET=ocean
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=octopusoctopus

  
  tentaclebridge:
    build: ./server
    image: harry/tentacle-bridge
    container_name: tentacle-bridge
    depends_on:
      - mosquitto
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb:
  grafana-storage:
    